# Generated by Django 5.0.2 on 2024-07-08 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do paciente', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('endereco', models.CharField(help_text='Digite o endereço completo', max_length=100, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Endereço')),
                ('cidade', models.CharField(help_text='Digite a cidade', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cidade')),
                ('tipo_alergia', models.CharField(choices=[('FOOD', 'Comida'), ('DRUG', 'Medicamentos'), ('INSECT', 'Insetos'), ('OTHER', 'Outros')], help_text='Selecione o tipo  de alergia', max_length=50, verbose_name='Tipo de Alergia')),
                ('alergias', models.CharField(blank=True, help_text='Digite todas as alergias', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Alergias')),
                ('telefone', models.CharField(help_text='Digite o telefone com DDD', max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Tel')),
                ('telefone_emergencia', models.CharField(help_text='Digite o telefone para Emergências com DDD', max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefone de Emergência')),
                ('nome_contato', models.CharField(help_text='Digite o nome do contato', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome para Contato')),
                ('parentesco', models.CharField(help_text='Digite o parentesco do contato', max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Parentesco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
