# Generated by Django 5.0 on 2024-07-08 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('endereco', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(20)])),
                ('cidade', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tipo_alergia', models.CharField(choices=[('FOOD', 'comida'), ('DRUG', 'medicamento'), ('INSECT', 'insetos'), ('OTHER', 'outros')], default='FOOD', max_length=20)),
                ('alergias', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('tel_emergencia', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nome_contato', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('parentesco', models.CharField(choices=[('FATHER', 'pai'), ('MOTHER', 'mãe'), ('PARTNER', 'conjuge'), ('OTHER', 'outro')], default='OTHER', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('reconsulta', models.BooleanField()),
                ('exames', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('encaminhamento', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('plano', models.CharField(choices=[('UNIMED', 'Unimed'), ('DOCTOR_CLIN', 'Doctor Clin'), ('PUBLIC', 'Publico'), ('PRIVATE', 'Particular')], default='PUBLIC', max_length=20)),
                ('prioridade', models.CharField(choices=[('LOW', 'baixa'), ('MEDIUM', 'media'), ('HIGH', 'alta'), ('URGENCY', 'urgencia')], default='LOW', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
